name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pycodestyle
      run: pip install pycodestyle
    - name: Run pycodestyle
      run: pycodestyle .
